#!/usr/bin/env python
from __future__ import division
from __future__ import print_function
from __future__ import absolute_import
from avutils import file_processing as fp
from avutils import util


def shuffle_corresponding_lines(options):
    arrays_of_lines = fp.read_rows_into_arr(
        fp.get_file_handle(file_name) for file_name in options.file_names)
    shuffled_arrays = util.shuffled_arrays(arrays_of_lines,
                                           copy_on_shuffle=False)
    for shuffled_array, file_name in zip(shuffled_arrays, options.file_names):
        shuffled_file_name = util.get_file_name_parts(file_name)\
                                .get_transformed_file_path(
                                  transformation=lambda x: "shuffled_"+x)
        fp.write_to_file("\n".join(shuffled_array)) 
     

if __name__ == "__main__":
    import argparse;
    parser = argparse.ArgumentParser("Shuffle lines of files correspondingly")
    parser.add_argument("file_names", nargs="+") 
    options = parser.parse_args()
    shuffle_corresponding_lines(options)
